on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"
    tags:
      - "*"
jobs:
  job1:
    env:
       # refs/tags/v: tag v 開頭是 production
      ENVIORMENT: ${{ startsWith(github.ref, 'refs/tags/v') && 'production' || 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Say hello # name：A name for your step to display on GitHub.
        run: |
          echo "Hello"
          echo "$ENVIORMENT"

      - name: Try to fail (continue-on-error)
        id: continue_on_error # id： 可給可不給，不給的話無法在 context 中取得
        continue-on-error: true # continue-on-error 這個步驟失敗，但不會影響後續步驟
        run: exit 1

      - name: Try to fail (no_continue_on_error)
        id: no_continue_on_error # id： 可給可不給，不給的話無法在 context 中取得
        run: exit 1

      - name: Say world
        run: echo "World"

      - name: print_steps_result
        if: ${{ failure() }}
        run: |
          echo "steps.continue_on_error.conclusion ${{steps.continue_on_error.conclusion}}" # after continue-on-error: success
          echo "steps.continue_on_error.outcome ${{steps.continue_on_error.outcome}}" # before continue-on-error failure
          
          echo "steps.no_continue_on_error.conclusion ${{steps.no_continue_on_error.conclusion}}" # after continue-on-error: failure
          echo "steps.no_continue_on_error.outcome ${{steps.no_continue_on_error.outcome}}" # after continue-on-error: failure

      - name: failed
        if: ${{ failure() }}
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: "${{ secrets.LINE_ACCESS_TOKEN }}"
          message: "one of steps has faild"

      - name: failed_continue_on_error
        if: ${{ failure() &&  steps.continue_on_error.conclusion == 'failure' }}
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: "${{ secrets.LINE_ACCESS_TOKEN }}"
          message: "continue_on_error conclusion step has faild"

      - name: failed_no_continue_on_error
        if: ${{ failure() &&  steps.no_continue_on_error.conclusion == 'failure' }}
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: "${{ secrets.LINE_ACCESS_TOKEN }}"
          message: "no_continue_on_error conclusion has faild"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Say hello
        run: echo "Job2 Hello"

      - name: failed # 這邊抓不到 job1 的 failure 結果，因為是不同 job
        if: ${{ failure() }} 
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: "${{ secrets.LINE_ACCESS_TOKEN }}"
          message: "job2 something faild"